import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;

public class reg extends javax.swing.JFrame {
    Connection con=null;
    PreparedStatement ps=null;
    Statement st=null;
    ResultSet rs=null,re=null, ro=null;
    int a=0,b=0,c=0;
    /**
     * Creates new form reg
     */
    public reg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        addr = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        quali = new javax.swing.JComboBox<>();
        gender = new javax.swing.JComboBox<>();
        email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        confirm = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        rollno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISERTATION FORM");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 51));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 323, 216, 45));

        jLabel1.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel1.setText("Last Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 98, 121, 29));

        jLabel2.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 102, 0));
        jLabel2.setText("Frist Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 51, 121, 29));

        jLabel3.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 102, 0));
        jLabel3.setText("Address:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 150, 121, 29));

        jLabel4.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 102, 0));
        jLabel4.setText("Gender:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 185, 113, 29));

        jLabel5.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 102, 0));
        jLabel5.setText("Contact:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 99, 29));

        jLabel6.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 102, 0));
        jLabel6.setText("Password:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 227, 121, -1));

        jLabel7.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 102, 0));
        jLabel7.setText("Qualification:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 108, 29));

        jLabel8.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 102, 0));
        jLabel8.setText("Email:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 236, 121, -1));

        fname.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 182, -1));

        addr.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        getContentPane().add(addr, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 152, 182, -1));

        lname.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 100, 182, -1));

        contact.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 191, -1));

        quali.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        quali.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "10th", "12th", "Graduated", "Post Graduated" }));
        getContentPane().add(quali, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 188, -1));

        gender.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Others" }));
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 186, 130, -1));

        email.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 18)); // NOI18N
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 277, 335, 39));

        jLabel9.setFont(new java.awt.Font("Felix Titling", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("REGISERTATION FORM");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        password.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 278, 279, 39));

        jLabel10.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 102, 0));
        jLabel10.setText("Confirm Password:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 323, 212, -1));

        confirm.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        getContentPane().add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 358, 279, 39));

        jLabel11.setText("If you are have already registered so,");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 391, -1, -1));

        jButton2.setText("click here");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 386, -1, 26));

        rollno.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        getContentPane().add(rollno, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 191, -1));

        jLabel13.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 102, 0));
        jLabel13.setText("Roll Number:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 108, 29));

        jLabel14.setBackground(new java.awt.Color(153, 204, 255));
        jLabel14.setForeground(new java.awt.Color(0, 51, 51));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String s="Select";
       String pas=password.getText();
        String cof=confirm.getText();
        
        
       
          
        if(fname.getText(). trim(). isEmpty()){
             JOptionPane.showMessageDialog(reg.this, "!!! ENTER First Name");
             fname.grabFocus();
             return;
         }
          if(lname.getText(). trim(). isEmpty()){
             JOptionPane.showMessageDialog(reg.this, "!!! ENTER Last Name");
             lname.grabFocus();
             return;
         }
           if(addr.getText(). trim(). isEmpty()){
             JOptionPane.showMessageDialog(reg.this, "!!! ENTER Address");
             addr.grabFocus();
             return;
         }
            if(gender.getSelectedItem().toString().equals(s)){
         
                JOptionPane.showMessageDialog(reg.this, "!!! Select your gender ");
             gender.grabFocus();
             return;
            }
             if(contact.getText(). trim(). isEmpty()){
             JOptionPane.showMessageDialog(reg.this, "!!! ENTER Contact");
             contact.grabFocus();
             return;
         }
                if(rollno.getText(). trim(). isEmpty() ){
             JOptionPane.showMessageDialog(reg.this, "!!! ENTER Roll Number");
             rollno.grabFocus();
             return;
         }
                if(quali.getSelectedItem().toString().equals(s)){
         JOptionPane.showMessageDialog(reg.this, "!!! Select your Qualification ");
             quali.grabFocus();
             return;
            }
                if(email.getText(). trim(). isEmpty()){
             JOptionPane.showMessageDialog(reg.this, "!!! ENTER Email");
             email.grabFocus();
             return;
         }
                if(password.getText(). trim(). isEmpty()){
             JOptionPane.showMessageDialog(reg.this, "!!! ENTER Password");
             password.grabFocus();
             return;
         }
                   if(cof == confirm.getText() ? pas != password.getText() : !cof.equals(pas)){
              JOptionPane.showMessageDialog(reg.this, "!!! Your confirm password is not correct !!! try again");
             confirm.setText("");
             confirm.grabFocus();
             return;         
             } 
                   
                   try{
                         con=DriverManager.getConnection("jdbc:mysql://localhost:3306/userreg","root","");
           // String query ="INSERT INTO `student`(`FristName`, `LastName`, `Address`, `Gender`, `Contact`, `Qualification`, `Email`, `Password`) VALUES (?,?,?,?,?,?,?,?)";
           // ps=con.prepareStatement(query);
                String rol="Select rollno from student where rollno='"+rollno.getText()+"'";
                 st=con.createStatement();
            ro=st.executeQuery(rol);
            if(ro.next() == false){
                 c=1;
            } 
                   }catch(Exception x){
                   x.printStackTrace();}
                       
    

                   try{
                         con=DriverManager.getConnection("jdbc:mysql://localhost:3306/userreg","root","");
           // String query ="INSERT INTO `student`(`FristName`, `LastName`, `Address`, `Gender`, `Contact`, `Qualification`, `Email`, `Password`) VALUES (?,?,?,?,?,?,?,?)";
           // ps=con.prepareStatement(query);
                String cop="Select contact from student where contact='"+contact.getText()+"'";
                 st=con.createStatement();
            re=st.executeQuery(cop);
            if(re.next() == false){
                b=1;
            }
                   }catch(Exception ex){
                   ex.printStackTrace();
                   }finally{
                   if(con!=null){
                                  try {
              con=DriverManager.getConnection("jdbc:mysql://localhost:3306/userreg","root","");
            String query ="INSERT INTO `student`(`FristName`, `LastName`, `Address`, `Gender`, `Contact`, `Qualification`, `Email`, `Password`, `rollno`) VALUES (?,?,?,?,?,?,?,?,?)";
            ps=con.prepareStatement(query);
             String comp="Select email from student where email='"+email.getText()+"'";
          //    String cop="Select contact from student where contact='"+contact.getText()+"'";
               st=con.createStatement();
            
               rs=st.executeQuery(comp);
            if(rs.next() == false   ){
                a=1;
            }
              if(a!=1 ){    JOptionPane.showMessageDialog(reg.this, "!!! Email ID is Already exist");
          //  contact.setText("");
            email.setText("");
            password.setText("");
            confirm.setText("");
         email.grabFocus();
            return;
              }if(b!=1){
                 JOptionPane.showMessageDialog(reg.this, "Your contact already exixt enter different");
                contact.grabFocus();
                contact.setText(""); 
                return;   
              }
              if(c!=1){
                 JOptionPane.showMessageDialog(reg.this, "Roll no is already taken insert different");
                rollno.grabFocus();
                rollno.setText(""); 
                return;   
              }if(a==1 && b==1){
                if(c==1){
            ps.setString(1, fname.getText());
            ps.setString(2, lname.getText());
            ps.setString(3, addr.getText());
            ps.setString(4, gender.getSelectedItem().toString());
            ps.setString(5, contact.getText());
            ps.setString(6, quali.getSelectedItem().toString());
            ps.setString(7, email.getText());
            ps.setString(8, password.getText());
            ps.setString(9, rollno.getText());
            ps.executeUpdate();
                  String backupDir = "";
            JOptionPane.showMessageDialog(reg.this, "Your Regisertion Successfully done:'"+backupDir+"'.","Backup problem",JOptionPane.PLAIN_MESSAGE);
              }
              }
               fname.setText("");
            lname.setText("");
            addr.setText("");
            gender.setSelectedIndex(0);
            contact.setText("");
            quali.setSelectedIndex(0);
            email.setText("");
            password.setText("");
            confirm.setText("");
            rollno.setText("");
           //con.close();
        } catch (SQLException ex) {
          Logger.getLogger(reg.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(reg.this, ex);
        }
                   }
                       }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new sign_up().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addr;
    private javax.swing.JPasswordField confirm;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lname;
    private javax.swing.JPasswordField password;
    private javax.swing.JComboBox<String> quali;
    private javax.swing.JTextField rollno;
    // End of variables declaration//GEN-END:variables
}
