
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.Date;
import net.proteanit.sql.DbUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AMIT AND FAMILY
 */
public class Update extends javax.swing.JFrame {
     Connection con =null;
    Statement stmt=null,st=null;
      PreparedStatement ps=null;
    ResultSet rs,re;
     int a;
     int b;
     int c=0,d=0,e=0;

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        roll = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        addr = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        contact = new javax.swing.JTextField();
        quali = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("STUDENT UPDATE PAGE");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 36)); // NOI18N
        jLabel1.setText("UPDATE STUDENT DETIALS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 18, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel2.setText("ENTER STUDENT ROLL NUMNER:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 74, -1, -1));
        getContentPane().add(roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 74, 182, -1));

        jLabel4.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 102, 0));
        jLabel4.setText("Last Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 177, 104, 29));

        jLabel9.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 102, 0));
        jLabel9.setText("Frist Name:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 142, 109, 29));

        jLabel11.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 102, 0));
        jLabel11.setText("Address:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 215, 88, 29));

        jLabel12.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 102, 0));
        jLabel12.setText("Contact:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 142, 77, 29));

        jLabel13.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 102, 0));
        jLabel13.setText("Qualification:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 177, 108, 29));

        jLabel14.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 102, 0));
        jLabel14.setText("Gender:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 215, 75, 29));

        fname.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 144, 205, -1));

        lname.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 179, 204, -1));

        addr.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        getContentPane().add(addr, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 217, 204, -1));

        gender.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Others" }));
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 216, 130, -1));

        contact.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 144, 191, -1));

        quali.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        quali.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "10th", "12th", "Graduated", "Post Graduated" }));
        getContentPane().add(quali, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 178, 188, -1));

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 74, -1, 56));

        jLabel3.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel3.setText("ENTER STUDENT PASSWORD:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 104, -1, -1));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 104, 182, -1));

        jButton2.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 153, 0));
        jButton2.setText("Update ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 262, 204, 43));

        jButton3.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 153, 0));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 262, 204, 43));

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 310, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\AMIT AND FAMILY\\Downloads\\700.350.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(roll.getText(). trim(). isEmpty()){
             JOptionPane.showMessageDialog(Update.this, "!!! ENTER ROLL NUMBER");
             roll.grabFocus();
             return;
         }if(password.getText(). trim(). isEmpty()){
         JOptionPane.showMessageDialog(Update.this, "!!!! Enter password ");
         password.grabFocus();
         return;
         }
          try{
             //Class.forName("com.mysql.cj.jdbc.Driver");
      con=DriverManager.getConnection("jdbc:mysql://localhost:3306/userreg","root","");
      stmt= con.createStatement();
     rs = stmt.executeQuery("select * from userreg.student ;");
    // String fname = rs.getString(1);
     System.out.print("");
     while(rs.next()){
     String e=rs.getString(9);
     String p=rs.getString(8);
     String em=roll.getText();
     String pas=password.getText();
     
      if(em.equals(e)){
           a=1;
       //  JOptionPane.showMessageDialog(sign_up.this, "");
        
     }if(pas.equals(p)){
     b=1;
       
     }if(a==1&& b==1){
         // JOptionPane.showMessageDialog(Update.this, "Your Login Successfully correct");
      System.out.println("login rigth");
      a=0; b=0; c=1;
       roll.setText(""+roll.getText());
     password.setText(""+password.getText());
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/userreg","root","");
        String query="Select*from student where student.password='"+password.getText()+"'";
        Statement sts=con.createStatement();
        rs=sts.executeQuery(query);
     if(rs.next()){
       fname.setText(""+rs.getString(1));
          lname.setText(""+rs.getString(2));
          addr.setText(""+rs.getString(3));
          gender.setSelectedItem(""+rs.getString(4));
          contact.setText(""+rs.getString(5));
          quali.setSelectedItem(""+rs.getString(6));
        }
     d=1;
    //  new tablepick().setVisible(true);
     }
     }    
     if(c!=1){
     JOptionPane.showMessageDialog(Update.this, "!!! wrong entiers");
     JOptionPane.showMessageDialog(Update.this, "try again");
     roll.setText("");
     password.setText("");
     }
     con.close();
      }catch(SQLException e){
          System.err.print("go to exception!!!");
          System.err.println(e.getMessage());
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      new sign_up().setVisible(true);
        dispose();
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    if(d!=1){
    JOptionPane.showMessageDialog(Update.this, "!!! Frist show your detials");
    return;
    }
        try{
         con=DriverManager.getConnection("jdbc:mysql://localhost:3306/userreg","root","");
       //  System.out.print("1");
            String query ="update student set fristname='"+fname.getText()+"',lastname='"+lname.getText()+"',address='"+addr.getText()+"',contact='"+contact.getText()+"',qualification='"+quali.getSelectedItem().toString()+"',gender='"+gender.getSelectedItem().toString()+"' where rollno='"+roll.getText()+"'";
           ps=con.prepareStatement(query);
             st=con.createStatement();
       // re=st.executeQuery(query);
      if(d==1){
            ps.executeUpdate(); 
                           String f = fname.getText();
                   String l = lname.getText();
                   String s = addr.getText();
                   String w = gender.getSelectedItem().toString();
                   String co = contact.getText();
                   String qu = quali.getSelectedItem().toString();
                   String dir="=============================";
            JOptionPane.showMessageDialog(null, "Frist Name:  "+f+"\nLast Name:  "+l+"\nAddress:  "+s+"\nGender:  "+w+"\nQualification:  "+qu+"\nContact:  "+co+"\n"+dir+"\n\tYour Update Successfully Completed\n"+dir+".","UPDATE DONE",JOptionPane.PLAIN_MESSAGE);
    
      //JOptionPane.showMessageDialog(Update.this, "your update Successfully completed");
        fname.setText("");
          lname.setText("");
          addr.setText("");
          gender.setSelectedItem(0);
          contact.setText("");
          quali.setSelectedItem(0);
          password.setText("");
          roll.setText("");
             Update up = new Update();
     up.setVisible(true);
     setVisible(false);
     dispose();
         
      }else{
      JOptionPane.showMessageDialog(Update.this, "Something went wrong !!!!!");
      }
      }catch(Exception ex){
       System.err.print("go to exception!!!");
          System.err.println(ex.getMessage());}
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(d!=1){
    JOptionPane.showMessageDialog(Update.this, "!!! Frist show your detials");
    return;
    }
       
      int yn =  JOptionPane.showConfirmDialog(Update.this, "Are you sure Delete your deletes?","WARNING", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
       if(yn == JOptionPane.YES_OPTION){
       System.out.println("yes button clicked");
       e=1;
       }else if(yn==JOptionPane.NO_OPTION){
    System.out.println("no button clicked");
    JOptionPane.showMessageDialog(Update.this, "Your Detials can not Deleted");
    }else if(yn==JOptionPane.CLOSED_OPTION){
    System.out.println("closed");
    } 
       if(e==1){
        try{
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/userreg","root","");
            String query ="delete from student where rollno='"+roll.getText()+"'";
           ps=con.prepareStatement(query);
             st=con.createStatement();
          if(d==1){
          ps.executeUpdate();
          JOptionPane.showMessageDialog(Update.this, "!!!! Your Detials are deleted");
           fname.setText("");
          lname.setText("");
          addr.setText("");
          gender.setSelectedItem(0);
          contact.setText("");
          quali.setSelectedItem(0);
          password.setText("");
          roll.setText("");
          }else{
          JOptionPane.showMessageDialog(Update.this , "Something went wrong !!!");
          }   
        }catch(Exception xe){
        
        }
      }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addr;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField password;
    private javax.swing.JComboBox<String> quali;
    private javax.swing.JTextField roll;
    // End of variables declaration//GEN-END:variables
}
